//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface APCheckConfig : MMObject <WCTTableCoding>
{
    int _configVersion;
    unsigned int _httpConnectTimeoutMillis;
    unsigned int _httpReadTimeoutMillis;
    NSString *_pingUrl;
    NSString *_threeTwoBlackUrl;
    NSString *_pingEnabled;
    NSString *_echoStr;
}

+ (const struct WCTProperty *)echoStr;
+ (const struct WCTProperty *)pingEnabled;
+ (const struct WCTProperty *)threeTwoBlackUrl;
+ (const struct WCTProperty *)pingUrl;
+ (const struct WCTProperty *)httpReadTimeoutMillis;
+ (const struct WCTProperty *)httpConnectTimeoutMillis;
+ (const struct WCTProperty *)configVersion;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(retain, nonatomic) NSString *echoStr; // @synthesize echoStr=_echoStr;
@property(retain, nonatomic) NSString *pingEnabled; // @synthesize pingEnabled=_pingEnabled;
@property(retain, nonatomic) NSString *threeTwoBlackUrl; // @synthesize threeTwoBlackUrl=_threeTwoBlackUrl;
@property(retain, nonatomic) NSString *pingUrl; // @synthesize pingUrl=_pingUrl;
@property(nonatomic) unsigned int httpReadTimeoutMillis; // @synthesize httpReadTimeoutMillis=_httpReadTimeoutMillis;
@property(nonatomic) unsigned int httpConnectTimeoutMillis; // @synthesize httpConnectTimeoutMillis=_httpConnectTimeoutMillis;
@property(nonatomic) int configVersion; // @synthesize configVersion=_configVersion;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

