//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol FileDetailLogicDelegate
- (void)onCanShareToFriendByButton;
- (void)onRevoked;
- (void)onDownloadFileProgress:(double)arg1;
- (void)onDownloadFileSuccess;
- (void)onDownloadFileFail:(_Bool)arg1;
@end

