//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FileDetailLogicController : NSObject
{
    id <FileDetailLogicDelegate> _m_fileDetailLogicDelegate;
}

@property(nonatomic) __weak id <FileDetailLogicDelegate> m_fileDetailLogicDelegate; // @synthesize m_fileDetailLogicDelegate=_m_fileDetailLogicDelegate;
- (void).cxx_destruct;
- (id)GetFileName;
- (id)GetTmpFilePath;
- (id)GetFilePath;
- (unsigned long long)GetFileSize;
- (id)GetForwardData;
- (unsigned int)GetPreviewType;
- (_Bool)canShowFTSAction;
- (_Bool)canAddToFavorites;
- (_Bool)canShowMsgForwardTo3rdApp;
- (_Bool)autoDownload;
- (_Bool)isDownloading;
- (void)OnAddToFavorites;
- (void)onApplyToFTS;
- (void)OnForwardTo3rdApp:(id)arg1;
- (void)OnForwordWithViewController:(id)arg1;
- (_Bool)OnPreviewFile:(unsigned int)arg1;
- (void)checkIsFileExistInSvr;
- (void)stopDownload;
- (void)startDownload;

@end

