//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface FTSMsgUserNameIdItem : NSObject <WCTTableCoding>
{
    _Bool isAutoIncrement;
    unsigned int userNameId;
    unsigned int validFlag;
    unsigned int tableId;
    unsigned int preCursorMesId;
    unsigned int nextCursorMesId;
    NSString *userName;
    long long lastInsertedRowID;
}

+ (const struct WCTProperty *)nextCursorMesId;
+ (const struct WCTProperty *)preCursorMesId;
+ (const struct WCTProperty *)tableId;
+ (const struct WCTProperty *)userName;
+ (const struct WCTProperty *)validFlag;
+ (const struct WCTProperty *)userNameId;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) _Bool isAutoIncrement; // @synthesize isAutoIncrement;
@property(nonatomic) unsigned int nextCursorMesId; // @synthesize nextCursorMesId;
@property(nonatomic) unsigned int preCursorMesId; // @synthesize preCursorMesId;
@property(nonatomic) unsigned int tableId; // @synthesize tableId;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;
@property(nonatomic) unsigned int validFlag; // @synthesize validFlag;
@property(nonatomic) unsigned int userNameId; // @synthesize userNameId;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

