//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface FTSWebSearchUtil : MMObject
{
}

+ (id)makeGeneralFailParam;
+ (id)makeEmptyJSONResultParam;
+ (id)getHightlightString:(id)arg1 searchText:(id)arg2 matchWordTip:(id)arg3;
+ (id)makeJSONResultParamWithQuery:(id)arg1 allContacts:(id)arg2 sortedArray:(id)arg3 offset:(long long)arg4 count:(long long)arg5;
+ (id)getWebViewPresetUI:(id)arg1;
+ (id)tryGetNavTitleWithParams:(id)arg1;
+ (int)convertViewTypeWithViewTypeStr:(id)arg1;
+ (id)tryAppendNewKeyForUrlStr:(id)arg1 andKey:(id)arg2 andUrlParams:(id)arg3;
+ (_Bool)applyToDevelopH5:(id)arg1;
+ (void)deleteDevelopH5;
+ (id)pathForDevelopH5;
+ (id)pathForDevelopH5Dir;
+ (unsigned int)getVersionForDevelopH5;
+ (_Bool)verifyDevelopH5;
+ (_Bool)isUseDevelopH5;
+ (int)verifyModuleContent:(id)arg1;
+ (id)GenerateSearchSessionUniqeID:(unsigned int)arg1;
+ (void)removeUpdatedH5;
+ (void)removeGuideDataForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2;
+ (void)removeAllGuideData;
+ (id)getSearchGuideDataForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2 andBysinessType:(unsigned long long)arg3;
+ (_Bool)cacheGuideData:(id)arg1 forScene:(unsigned int)arg2 andVersion:(unsigned int)arg3 andBusinessType:(unsigned long long)arg4;
+ (_Bool)cacheGuideData:(id)arg1 forScene:(unsigned int)arg2 andVersion:(unsigned int)arg3;
+ (_Bool)shouldUpdateGuideDataForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2;
+ (id)pathForGuideCacheForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2 andBusinessType:(unsigned long long)arg3;
+ (id)pathForGuideCacheForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2;
+ (id)pathForGuideCacheForScene:(unsigned int)arg1;
+ (id)pathForGuideCache;
+ (id)pathForGuideCacheDir;
+ (id)makeDictionaryFromPath:(id)arg1;
+ (void)reloadDownloadConfig;
+ (void)reloadDefaultConfig;
+ (unsigned int)getVersionForUpdateH5;
+ (unsigned int)getVersionForDefaultH5;
+ (id)pathForUpdatedGuidePage;
+ (id)pathForIOS8WKH5;
+ (id)pathForUpdatedH5;
+ (id)pathForUpdatedH5Dir;
+ (id)pathForH5Root;
+ (id)pathForDefaultH5;
+ (id)pathForDefaultH5Dir;
+ (id)pathForMainH5Dir;
+ (id)pathForMainH5;
+ (unsigned int)getVersion;
+ (_Bool)isUpdatedGuidePageExist;
+ (_Bool)isUpdatedH5Exist;
+ (id)searchTextField:(id)arg1 shouldChangeRange:(struct _NSRange)arg2 replaceText:(id)arg3 shouldNotify:(_Bool *)arg4;
+ (id)formatMultiStageInputText:(id)arg1;

@end

