//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ProtobufCGIWrap;

@protocol IDCHostMgrExt <NSObject>

@optional
- (void)onRsaVerifyFaceAgain:(ProtobufCGIWrap *)arg1;
- (void)onRsaRegisterFaceAgain:(ProtobufCGIWrap *)arg1;
- (void)onRsaGetBioConfigAgain:(ProtobufCGIWrap *)arg1;
- (void)OnGetVoicePrintLoginTicketAgain:(ProtobufCGIWrap *)arg1;
- (void)OnRegAgain;
- (void)BindMobileAgain:(ProtobufCGIWrap *)arg1;
@end

