//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBMessageObserverDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet;

@interface InfrequentContactsDataLogic : NSObject <PBMessageObserverDelegate>
{
    _Bool m_bHasLoadData;
    _Bool m_bIsLoadDataLoading;
    _Bool m_bHasLoadSNS;
    _Bool m_bHasLoadOther;
    unsigned char m_uiLoadSNSStatus;
    NSMutableSet *m_nInfrequentContactSet;
    NSMutableSet *m_infrequentContactSet;
    NSMutableSet *m_infrequentMomentSet;
    NSMutableSet *m_nHasnotSameGroupSet;
    NSMutableSet *m_hasnotSameGroupSet;
    NSMutableArray *m_groupArray;
    NSMutableDictionary *m_dicFilterItem;
    id <InfrequentContactsDataLogicDelegate> _delegate;
}

@property(nonatomic) __weak id <InfrequentContactsDataLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)initDataDone;
- (_Bool)isInfrequentMoment:(id)arg1;
- (_Bool)hasnotSameGroup:(id)arg1;
- (_Bool)isInfrequentContact:(id)arg1;
- (_Bool)onFilterContactCandidate:(id)arg1;
- (_Bool)isSNSDataError;
- (_Bool)shouldSNSDataWait;
- (void)initData;
- (void)doSnsDataRequest;
- (id)getFilters;
- (void)updateWithFilters:(id)arg1;
- (void)dealloc;

@end

