//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface InfrequentContactFilterItem : NSObject
{
    _Bool _m_bOpen;
    unsigned int _m_uiType;
    NSString *_m_nsDetail;
}

+ (id)itemWithItem:(id)arg1;
+ (id)itemWithType:(unsigned int)arg1 open:(_Bool)arg2 detail:(id)arg3;
@property(retain, nonatomic) NSString *m_nsDetail; // @synthesize m_nsDetail=_m_nsDetail;
@property(nonatomic) _Bool m_bOpen; // @synthesize m_bOpen=_m_bOpen;
@property(nonatomic) unsigned int m_uiType; // @synthesize m_uiType=_m_uiType;
- (void).cxx_destruct;

@end

