//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol IWAMsgNodeRequestMgrExt <NSObject>

@optional
- (void)onRequestMgrSendRequest:(NSString *)arg1 callbackId:(NSString *)arg2 resp:(NSString *)arg3 nextReqTime:(unsigned int)arg4;
@end

