//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSMutableArray, NSString;

@interface LoginInfo : NSObject <PBCoding>
{
    NSMutableArray *m_arrUserInfos;
}

+ (void)saveLoginInfo:(id)arg1;
+ (id)loadLoginInfo;
+ (id)getLoginInfoPath;
+ (void)clearLocalInfo;
+ (id)userInfoFromLocalInfo;
+ (void)initialize;
@property(retain, nonatomic) NSMutableArray *m_arrUserInfos; // @synthesize m_arrUserInfos;
- (void).cxx_destruct;
- (void)reportOpCode:(unsigned int)arg1 Index:(unsigned int)arg2;
- (id)getUserInfo:(id)arg1;
- (void)updateWithLoginUserInfo:(id)arg1;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

