//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IMMChatContentUploadLogicExt.h"
#import "MMKernelExt.h"
#import "MessageObserverDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface MMChatContentUploadLogic : MMObject <MessageObserverDelegate, IMMChatContentUploadLogicExt, MMKernelExt>
{
    NSObject<OS_dispatch_queue> *_queue;
    _Bool _validSync;
    NSMutableArray *_savedSessionInfoArr;
    NSMutableArray *_reportSessionInfoArr;
}

@property(nonatomic) _Bool validSync; // @synthesize validSync=_validSync;
@property(retain, nonatomic) NSMutableArray *reportSessionInfoArr; // @synthesize reportSessionInfoArr=_reportSessionInfoArr;
@property(retain, nonatomic) NSMutableArray *savedSessionInfoArr; // @synthesize savedSessionInfoArr=_savedSessionInfoArr;
- (void).cxx_destruct;
- (void)onExtChatUploadReplyChat:(id)arg1;
- (void)onExtChatUploadLeaveChat:(id)arg1;
- (void)onExtChatUploadEnterChat:(id)arg1;
- (void)MessageReturn:(unsigned int)arg1 MessageInfo:(id)arg2 Event:(unsigned int)arg3;
- (void)onPreQuit;
- (void)WillTerminate:(id)arg1;
- (void)DidEnterForeground:(id)arg1;
- (void)DidEnterBackground:(id)arg1;
- (void)report:(_Bool)arg1;
- (void)checkAndCompareData:(id)arg1;
- (void)saveCurrentData:(id)arg1;
- (void)recoverFormerData;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

