//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PoseDetect : NSObject
{
    struct PoseLivenessDetector *liveDetector;
}

+ (id)sharedManager;
- (_Bool)livePoseDetect:(struct _TC_FaceShape)arg1 withbLiveNessDetect:(_Bool *)arg2 withLiveType:(int)arg3 withImg:(struct Mat *)arg4 withRes:(int *)arg5;
- (void)resetPoseDetect;
- (id)init;

@end

