//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "ISearchConfigDataExt.h"
#import "SGRecommendDelegate.h"
#import "SGTopEntryViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class MMScrollView, NSString, SGRecomendPanel, SGTopEntryView, SearchCgiGuideConfig, UIView, WAShowOutInfo;

@interface SearchGuideView : MMUIView <ISearchConfigDataExt, SGTopEntryViewDelegate, SGRecommendDelegate, UIScrollViewDelegate>
{
    UIView *_whiteLayerView;
    MMScrollView *_scrollView;
    UIView *_ftsEntryView;
    SGTopEntryView *_topEntryView;
    SGRecomendPanel *_waRecmdPanel;
    SearchCgiGuideConfig *_vertInfo;
    WAShowOutInfo *_waInfo;
    id <SearchGuideViewDelegate> _delegate;
}

@property(nonatomic) __weak id <SearchGuideViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onCancelInteractivePush;
- (void)onFinishInteractivePush;
- (void)onTouchUpdateInteractivePushPercent:(double)arg1;
- (void)onTouchBeginInteractivePush;
- (void)onClickWeAppOutItem:(id)arg1;
- (void)onLaunchWeAppList;
- (void)onClickWithData:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)onSearchConfigDataUpdated;
- (void)onSearchConfigDataFailToUpdate;
- (void)updateDynamicView;
- (void)updateWeAppInfo;
- (void)updateDynamicData;
- (void)layoutWeAppRecmdView;
- (void)layoutSubviews;
- (void)hideKeyboard;
- (void)scrollViewDidScroll:(id)arg1;
- (void)ontap;
- (void)onTapBarButton:(id)arg1;
- (void)updateViewsAnimated:(_Bool)arg1;
- (void)initView;
- (void)hideContentViewAnimated:(_Bool)arg1;
- (void)showContentViewAnimated:(_Bool)arg1;
- (void)addBlurEffectForView:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

