//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface WAAppItemData : MMObject <WCTTableCoding>
{
    _Bool beStared;
    unsigned int appType;
    unsigned int updateTime;
    NSString *userName;
}

+ (const struct WCTProperty *)beStared;
+ (const struct WCTProperty *)updateTime;
+ (const struct WCTProperty *)appType;
+ (const struct WCTProperty *)userName;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(nonatomic) _Bool beStared; // @synthesize beStared;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime;
@property(nonatomic) unsigned int appType; // @synthesize appType;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;
- (void).cxx_destruct;
- (id)appItemKey;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

