//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class AVPlayer, NSString;

@interface WAAudioPlayer : MMObject
{
    long long _state;
    _Bool _shouldLoop;
    _Bool _obeyMuteSwitch;
    _Bool _autoPlayAfterSet;
    _Bool _hasFirstTimePlay;
    id <IWAAudioPlayerDelegate> _delegate;
    AVPlayer *_player;
    NSString *_appId;
    NSString *_audioId;
    NSString *_src;
    double _startTime;
    double _bufferTime;
}

@property(nonatomic) _Bool hasFirstTimePlay; // @synthesize hasFirstTimePlay=_hasFirstTimePlay;
@property(nonatomic) _Bool autoPlayAfterSet; // @synthesize autoPlayAfterSet=_autoPlayAfterSet;
@property(nonatomic) _Bool obeyMuteSwitch; // @synthesize obeyMuteSwitch=_obeyMuteSwitch;
@property(nonatomic) _Bool shouldLoop; // @synthesize shouldLoop=_shouldLoop;
@property(nonatomic) double bufferTime; // @synthesize bufferTime=_bufferTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSString *src; // @synthesize src=_src;
@property(retain, nonatomic) NSString *audioId; // @synthesize audioId=_audioId;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(nonatomic) __weak id <IWAAudioPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onPlayerItemFailedToPlayToEndTime:(id)arg1;
- (void)onPlayerDidFinishPlaying;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setState:(long long)arg1;
@property(readonly, nonatomic) long long state;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) double curTime;
- (_Bool)isIdle;
- (_Bool)isWaiting;
- (_Bool)isPaused;
- (_Bool)isPlaying;
- (_Bool)isSet;
- (void)setMute:(_Bool)arg1;
- (void)seekTo:(double)arg1;
- (void)stop;
- (void)pause;
- (void)activeAudioSession;
- (void)realPlay;
- (void)play;
- (void)setPlayerWithSrc:(id)arg1 url:(id)arg2 startTime:(double)arg3 autoPlay:(_Bool)arg4 loop:(_Bool)arg5 obeyMuteSwitch:(_Bool)arg6;
- (id)initWithAudioId:(id)arg1 appId:(id)arg2 delegate:(id)arg3;
- (void)removeObserver;
- (void)addObserver;
- (void)dealloc;

@end

