//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CAppBrandInfo;

@interface WAConfigContactAttribute : NSObject
{
    CAppBrandInfo *_appBrandInfo;
}

- (void).cxx_destruct;
- (id)downloadFileDomainList;
- (id)uploadFileDomainList;
- (id)webSocketDomainList;
- (id)requestDomainList;
- (unsigned int)lifeSpanAfterSuspend;
- (unsigned int)lifeSpanBeforeSuspend;
- (_Bool)canKeepAliveByAudioPlay;
- (unsigned int)backgroundNetworkInterruptedTimeout;
- (unsigned int)downloadFileMaxConcurrentCount;
- (unsigned int)uploadFileMaxConcurrentCount;
- (unsigned int)requestMaxConcurrentCount;
- (unsigned int)backgroundMaxRunningTimeInterval;
- (unsigned int)actualWebViewDepth;
- (unsigned int)webViewMaxDepth;
- (unsigned int)fileStorageMaxSizeMB;
- (unsigned int)localStorageMaxSizeMB;
- (id)initWithAppBrandInfo:(id)arg1;

@end

