//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSData, NSString;

@interface WAConfigInfo : NSObject <WCTTableCoding>
{
    unsigned int type;
    unsigned int version;
    unsigned int updateTime;
    NSString *appID;
    NSData *configData;
}

+ (const struct WCTProperty *)updateTime;
+ (const struct WCTProperty *)configData;
+ (const struct WCTProperty *)version;
+ (const struct WCTProperty *)type;
+ (const struct WCTProperty *)appID;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime;
@property(retain, nonatomic) NSData *configData; // @synthesize configData;
@property(nonatomic) unsigned int version; // @synthesize version;
@property(nonatomic) unsigned int type; // @synthesize type;
@property(retain, nonatomic) NSString *appID; // @synthesize appID;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

