//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

@class NEHotspotHelperCommand, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface WAJSContextPlugin_WiFi : WAJSContextPluginBase
{
    _Bool m_registed;
    _Bool m_hasPreSet;
    NSMutableDictionary *m_wifiInfoMap;
    NEHotspotHelperCommand *m_retainCommand;
    NSMutableArray *m_scanWiFiList;
    NSObject<OS_dispatch_queue> *m_timerQueue;
    NSObject<OS_dispatch_source> *m_deliverTimer;
}

- (void).cxx_destruct;
- (void)deliverNetworkCommand:(id)arg1;
- (void)onDeliverNetworkCommandWhenTimeout;
- (void)cancelDeliverTimeoutTimer;
- (void)setDeliverTimeoutTimer;
- (void)handleCommandForLogoff:(id)arg1;
- (void)handleCommandForMaintain:(id)arg1;
- (void)handleCommandForPresentUI:(id)arg1;
- (void)handleCommandForAuthenticate:(id)arg1;
- (void)handleCommandForEvaluate:(id)arg1;
- (void)handleCommandForFilterScanList:(id)arg1;
- (void)handleHotspotWiFiCommand:(id)arg1;
- (id)connectedWiFi;
- (id)wifiInfoWithSSID:(id)arg1 BSSID:(id)arg2;
- (void)preSetWifiListInfo:(id)arg1;
- (_Bool)setWifiListInfo:(id)arg1;
- (_Bool)isSupportHotspotWifi;
- (_Bool)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (void)dealloc;
- (_Bool)canHandleWifiList;
- (void)unregisterWifiHandler;
- (void)registerWifiHandler;
- (id)init;

@end

