//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIPercentDrivenInteractiveTransition;

@interface WAJumpBackInteractiveTransition : NSObject <UIGestureRecognizerDelegate>
{
    UIPercentDrivenInteractiveTransition *_interactivePopTransition;
    id <WAJumpBackInteractiveTransitionDelegate> _delegate;
    double _progressFactor;
}

@property(nonatomic) double progressFactor; // @synthesize progressFactor=_progressFactor;
@property(nonatomic) __weak id <WAJumpBackInteractiveTransitionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleJumpBackInteractivePopGesture:(id)arg1;
- (_Bool)isInteracting;
- (id)interactivePopTransition;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

