//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray;

@interface WCAdDislikeInfo : NSObject <NSCoding>
{
    NSArray *_reasonList;
}

@property(retain, nonatomic) NSArray *reasonList; // @synthesize reasonList=_reasonList;
- (void).cxx_destruct;
- (id)validReasonList;
- (long long)validReasonCount;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

