//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol WCPayOfflinePayViewControllerDelegate <NSObject>
- (void)onOfflinePayPatternLockBlockErrorOutOfLimit;
- (void)OnWCPayOfflinePayNoCodeTipsViewEnableRefreshBtnAfterClick;
- (void)OnWCPayOfflinePayNoCodeTipsViewClickRefreshBtn;
- (void)StopOfflineGetMsg;
- (void)StartOfflineGetMsg;
- (void)onWCpayOfflinePayViewControllerClickF2fHongBaoBtn;
- (void)onWCPayOfflinePayViewControllerClickGroupPayBtn;
- (void)OnWCpayOfflinePayViewControllerClickReceiveMoneyBtn;
- (void)OnWCPayOfflinePayViewControllerAddNewCardBtnPress;
- (void)OnWCPayOfflinePayViewControllerSnapShotAlertGotoDetail;
- (void)OnWCPayOfflinePayViewControllerCloseAction;
- (void)OnWCPayOfflinePayViewControllerUnfreezeBtnDown;
- (void)OnWCPayOfflinePayViewControllerQuickChangeOfflinePayLimit;
- (void)OnWCPayOfflinePayViewControllerChangeOfflinePayLimit;
- (void)OnWCPayOfflinePayViewControllerCreateOfflinePay;
- (void)OnWCPayOfflinePayViewControllerBack;
@end

