//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCPayLQTOrderConfirmViewDelegate.h"

@class MMTableView, MMUILabel, NSString, RichTextView, UIButton, UITextField, WCPayLQTOrderConfirmView;

@interface WCPayLQTMoneyViewController : WCPayBaseViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate, ILinkEventExt, WCPayLQTOrderConfirmViewDelegate, WCActionSheetDelegate>
{
    _Bool _bCheckBoxSelect;
    id <WCPayLQTMoneyViewControllerDelegate> _delegate;
    MMTableView *_tableView;
    UIButton *_operationBtn;
    UITextField *_moneyTextField;
    MMUILabel *_invalidTipsLabel;
    RichTextView *_richTextView;
    WCPayLQTOrderConfirmView *_confirmView;
}

@property(nonatomic) _Bool bCheckBoxSelect; // @synthesize bCheckBoxSelect=_bCheckBoxSelect;
@property(retain, nonatomic) WCPayLQTOrderConfirmView *confirmView; // @synthesize confirmView=_confirmView;
@property(retain, nonatomic) RichTextView *richTextView; // @synthesize richTextView=_richTextView;
@property(retain, nonatomic) MMUILabel *invalidTipsLabel; // @synthesize invalidTipsLabel=_invalidTipsLabel;
@property(retain, nonatomic) UITextField *moneyTextField; // @synthesize moneyTextField=_moneyTextField;
@property(retain, nonatomic) UIButton *operationBtn; // @synthesize operationBtn=_operationBtn;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <WCPayLQTMoneyViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)shouldShowProfitWording;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)checkBtnClick:(id)arg1;
- (id)makeProtocolContentView;
- (_Bool)lqtProtocolCheck;
- (_Bool)canShowLQTProtocol;
- (void)onOrderConfirmViewPayWithEnPwd:(id)arg1;
- (void)onOrderConfirmViewCancel;
- (void)refreshBalanceContent;
- (void)showPwdConfirmViewWhenPreRedeemFundOk;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidChang:(id)arg1;
- (void)operationBtnClick;
- (void)leftBarButtonClick;
- (void)hideInvalidTipsLabel;
- (void)showInvalidTipsLabelWithContent:(id)arg1;
- (void)initInvalidTipsLabel;
- (void)makeBtnCellContentView:(id)arg1;
- (void)makeInputContentView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableViewProfitContentHeight;
- (double)tableViewBtnWithProtocolCellHeight;
- (double)tableViewBtnCellHeight;
- (double)tableViewInputContentCellHeight;
- (void)setupContentView;
- (void)viewDidLoad;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

