//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class UIButton, UIView;

@interface WCPrivacyPolicyToolBarView : MMUIView
{
    UIView *_separatorLine;
    id <WCPrivacyPolicyToolBarViewDelegate> _delegate;
    UIButton *_doneBtn;
    UIButton *_cancelBtn;
}

@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UIButton *doneBtn; // @synthesize doneBtn=_doneBtn;
@property(nonatomic) __weak id <WCPrivacyPolicyToolBarViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onClickCancel;
- (void)onClickDone;
- (void)layoutSubviews;

@end

