//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface WebRecordInfoData : MMObject <WCTTableCoding>
{
    unsigned int _visittime;
    NSString *_link;
    NSString *_name;
    NSString *_title;
    NSString *_iconurl;
    NSString *_imgurl;
}

+ (const struct WCTProperty *)visittime;
+ (const struct WCTProperty *)imgurl;
+ (const struct WCTProperty *)iconurl;
+ (const struct WCTProperty *)title;
+ (const struct WCTProperty *)name;
+ (const struct WCTProperty *)link;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(nonatomic) unsigned int visittime; // @synthesize visittime=_visittime;
@property(retain, nonatomic) NSString *imgurl; // @synthesize imgurl=_imgurl;
@property(retain, nonatomic) NSString *iconurl; // @synthesize iconurl=_iconurl;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *link; // @synthesize link=_link;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

