//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@class NSString, WebStorageConfigExt;

@interface WebStorageConfigTable : MMObject <WCTTableCoding>
{
    unsigned int _valueSize;
    unsigned int _expireTimestamp;
    unsigned int _lastModifyTime;
    NSString *_appId;
    NSString *_key;
    NSString *_weightStr;
    WebStorageConfigExt *_ext;
}

+ (const struct WCTProperty *)ext;
+ (const struct WCTProperty *)weightStr;
+ (const struct WCTProperty *)lastModifyTime;
+ (const struct WCTProperty *)expireTimestamp;
+ (const struct WCTProperty *)valueSize;
+ (const struct WCTProperty *)key;
+ (const struct WCTProperty *)appId;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(retain, nonatomic) WebStorageConfigExt *ext; // @synthesize ext=_ext;
@property(retain, nonatomic) NSString *weightStr; // @synthesize weightStr=_weightStr;
@property(nonatomic) unsigned int lastModifyTime; // @synthesize lastModifyTime=_lastModifyTime;
@property(nonatomic) unsigned int expireTimestamp; // @synthesize expireTimestamp=_expireTimestamp;
@property(nonatomic) unsigned int valueSize; // @synthesize valueSize=_valueSize;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

