//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ISysCallCheckExt.h"
#import "IVOIPUILogicMgrExt.h"

@class MMTimer, MMUILabel, NSString;

@interface WNParaVoiceTimeView : UIView <ISysCallCheckExt, IVOIPUILogicMgrExt>
{
    MMTimer *_recordTimer;
    unsigned int _startRecordTime;
    MMUILabel *_lengthLabel;
    id <WNVoiceTimeDelegate> _delegate;
}

@property(nonatomic) __weak id <WNVoiceTimeDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)BeginInterruption;
- (id)formatTimeCount:(int)arg1;
- (void)onTimeCount;
- (void)stopTimeCount;
- (void)startTimeCount;
- (void)initUI;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

