//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMWebSearchViewDelegate.h"

@class MMWebSearchController, NSString, UIView;

@interface WSLocalWebViewController : MMUIViewController <MMWebSearchViewDelegate>
{
    UIView *_navBarBkg;
    int _scene;
    MMWebSearchController *_webSearchController;
    unsigned long long _businessType;
    NSString *_contentTitle;
}

@property(retain, nonatomic) NSString *contentTitle; // @synthesize contentTitle=_contentTitle;
@property(nonatomic) unsigned long long businessType; // @synthesize businessType=_businessType;
- (void).cxx_destruct;
- (void)windowHide:(id)arg1;
- (void)onUpdateTitleViewWithTitle:(id)arg1;
- (double)webSearchViewPosY;
- (void)initView;
- (id)getTitleLabelWithTitle:(id)arg1;
- (void)updateTitleViewWithTitle:(id)arg1;
- (void)initTitleView;
- (void)onNavigationBackItemClick:(id)arg1;
- (void)initNavigationBar;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)useTransparentNavibar;
- (void)dealloc;
- (void)initWebSearchController;
- (id)initWithScene:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

