//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "EAAccessoryDelegate.h"
#import "MCProfileConnectionObserver.h"
#import "PSSplitViewControllerNavigationDelegate.h"
#import "UIApplicationDelegate.h"
#import "UISplitViewControllerDelegate.h"

@class EAAccessory, NSMutableSet, NSString, PSSplitViewController, PSUIPrefsRootController, UIWindow;

@interface PreferencesAppController : UIApplication <PSSplitViewControllerNavigationDelegate, UIApplicationDelegate, EAAccessoryDelegate, MCProfileConnectionObserver, UISplitViewControllerDelegate>
{
    PSSplitViewController *_splitViewController;
    PSUIPrefsRootController *_controller;
    UIWindow *_window;
    _Bool _isLocked;
    NSMutableSet *_busyControllers;
    _Bool _loadingExternalURL;
    unsigned long long _backgroundTaskHandle;
    double _timeoutLimit;
    _Bool _settingsWasResigned;
    unsigned int _rootDomainConnect;
    unsigned int _pmNotifier;
    struct IONotificationPort *_systemPowerPortRef;
    struct __CFRunLoopSource *_pmSource;
    EAAccessory *_speakerAccessory;
}

- (void).cxx_destruct;
- (void)_accessoryDidConnect:(id)arg1;
- (void)_clearSavedPositionURL;
- (void)_deregisterForPowerNotifications;
- (void)_handleBusyControllers;
- (void)_handleExternalApplicationChange;
- (void)_performURLHandlingForController:(id)arg1 dictionary:(id)arg2 items:(id)arg3 controllerNeedsPush:(_Bool)arg4;
- (void)_registerForPowerNotifications;
- (void)_resetSnapshotImage;
- (void)_setOffsetForController:(id)arg1 fromObjectPair:(id)arg2;
- (void)_suspendControllers;
- (void)accessoryDidDisconnect:(id)arg1;
- (void)addBusyControllersFromRootController:(id)arg1;
- (id)appWindow;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidResumeForEventsOnly;
- (void)applicationOpenURL:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillSuspendForEventsOnly;
- (void)applicationWillTerminate:(id)arg1;
- (void)clearControllersForSuspendedState;
- (void)controllerFinished:(id)arg1;
- (id)currentSpecifierIDPath;
- (void)dealloc;
- (double)defaultImageSnapshotExpiration;
- (void)endAndInvalidateBackgroundTask;
- (void)generateURL;
- (void)handleAuthKitURLIfNeededFromResourceDictionary:(id)arg1 overViewController:(id)arg2;
- (void)handleDeferredURLForSpecifierID:(id)arg1 resourceDictionary:(id)arg2;
- (void)handleDeferredURLForSpecifierID:(id)arg1 resourceDictionary:(id)arg2 objectOffsetPair:(id)arg3;
- (void)handleFamilyInviteChanged;
- (id)keyValueDictionaryForURL:(id)arg1;
- (id)oneTimeJumpURL;
- (void)popToRootOfSettingsSelectGeneral:(_Bool)arg1;
- (void)popToRootOfSettingsSelectGeneral:(_Bool)arg1 performWithoutDeferringTransitions:(_Bool)arg2;
- (id)preferredContentSizeCategory;
- (void)processAppPrefsURL:(id)arg1;
- (void)processURL:(id)arg1;
- (void)processURL:(id)arg1 animated:(_Bool)arg2 fromSearch:(_Bool)arg3;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)profileConnectionDidReceivePasscodeChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)profileConnectionDidReceiveProfileListChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)profileConnectionDidReceiveRestrictionChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)resetLocale;
- (id)rootController;
@property unsigned int rootDomainConnect; // @synthesize rootDomainConnect=_rootDomainConnect;
- (void)runScrollTest:(id)arg1 withOptions:(id)arg2;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
- (void)significantTimeChange;
- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
- (void)splitViewControllerDidPopToRootController:(id)arg1;
- (void)stopPlayback;
- (void)systemDidWake:(id)arg1;
- (void)updateFamilyInviteBadge;
- (void)updateSoftwareUpdateBadgeOnSpecifier:(id)arg1;
- (void)userDefaultsDidChange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

